### ISSUE TITLE
Formatting doesn't work with WSL2 hosted files in VS2022

### ISSUE THREAD

**Issue by Nekroido** [fsprojects/fantomas-for-vs#29]
Steps to reproduce:

- Create or open a solution/project hosted in WSL2;
- Open a .fs file you wish to format;
- Format the file with Edit > Advanced > Format Document.

Expected result:

The file is formatted according to the code style.

Actual result:

Nothing happens and no changes are introduced to the file.

Note:

Formatting works fine when I open projects in Windows host. Fantomas-tool is installed in both hosts and I can format files through both PowerShell in Windows and ZSH in WSL2 Debian.

**Comment by deviousasti** [comment]
Hey @Nekroido,
Sorry for the delayed reply.  I suspect it could be a permissions issue.
Here's the issue I'm seeing:

> Fantomas.Client tried to run `dotnet tool list` but exited with code 1. File dotnet-tools.json came from another computer and might be blocked to help protect this computer. For more information, including how to unblock, see https://aka.ms/motw

If there's a dotnet tool version defined in `dotnet-tools.json`, Fantomas tries to use that specific version.

**Comment by deviousasti** [comment]
It will work if there's no tool manifest defined - with the globally installed formatter.

**Comment by Nekroido** [comment]
Hi! Sorry, looks like I never pressed the "Comment" button.
I do have the manifest file, but only with the `paket` entry. The error I see in my "Output: F# Formatting" is this:
```
The operation is not supported:
 The FantomasResponseCode value '11' is unexpected.
```

**Comment by Nekroido** [comment]
The path exists in the Windows host. It also exists in my Debian host but without the `.exe` extension.

**Comment by nojaf** [comment]
Alright, can you execute the `exe` in the command line?
You shouldn't see anything, but if that crashes, that already tells us something.

**Comment by Nekroido** [comment]
Both executables exit with `Input path is missing...`

**Comment by nojaf** [comment]
Ah apologies, you need to add the `--daemon` flag.
So `C:\fullPath\fantomas.exe --daemon`

**Comment by Nekroido** [comment]
Both executables wait for the input and crash with the following trace when I press Enter:
```
Unhandled exception. StreamJsonRpc.BadRpcHeaderException: No Content-Length header detected.
   at StreamJsonRpc.HeaderDelimitedMessageHandler.ReadCoreAsync(CancellationToken cancellationToken)
   at StreamJsonRpc.MessageHandlerBase.ReadAsync(CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.ReadAndHandleRequestsAsync()
   at Program.main(String[] argv) in C:\Users\nojaf\Projects\fantomas\src\Fantomas.CoreGlobalTool\Program.fs:line 441
```

**Comment by nojaf** [comment]
Yeah, that sounds about right.
The error you get when pressing enter makes sense.
So, I can conclude here that the daemon can be started but not programmatically on your end.
There could be a bug in Fantomas.Client.

Could you create a script file with:
```fsharp
#r "nuget: Fantomas.Client"

open System.IO
open Fantomas.Client.Contracts
open Fantomas.Client.LSPFantomasService

let service = new LSPFantomasService() :> FantomasService

// TODO: change file path to existing file on your machine
let file = @"C:\Users\nojaf\Projects\HelloWorld\Math.fs"
let content = File.ReadAllText file

let response =
    service.FormatDocumentAsync { SourceCode = content; FilePath = file; Config = None }
    |> Async.AwaitTask
    |> Async.RunSynchronously

printfn "%A" response
```

What does that output?

**Comment by Nekroido** [comment]
I see this error:
```System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\nojaf\Projects\HelloWorld\Math.fs'.```

And it outputs a formatted document in Windows environment when I provide a valid absolute `\\wsl$\Debian\...` path. Same for Debian for a `/home/...` path.

I see the error you [mentioned initially](https://github.com/fsprojects/fantomas-for-vs/issues/29#issuecomment-1107891907) if I use `\\wsl.localhost\...` path.

**Comment by nojaf** [comment]
Yeah, the behaviour we see is starting to make some sense.
Something is going wrong when requests are made with UNIX paths inside the Windows host.

**Comment by abelbraaksma** [comment]
Just chiming in as I'm running into the exact same issue. Nothing happens when I try to execute `Format Document` (or a variant, like saving with format-on-save set to 'on'). I'm on Windows 10, VS 2022, all recent updates, F# 6.0 etc. Same output in the Output window:

```text
The operation is not supported:
 The FantomasResponseCode value '11' is unexpected.
```

Running the commands above work just like @Nekroido mentions.

**Comment by abelbraaksma** [comment]
Is there a way to get more detailed output, or to set it up for debugging?

**Comment by abelbraaksma** [comment]
Btw, this is _not WSL2_. However, I just found out that the formatting _does work correctly_ on an older .NET Framework project, using VS 2022. 

@nojaf, thanks, I'll give it a go.

**Comment by abelbraaksma** [comment]
@deviousasti, silly question, but I only installed this so far through Marketplace. Do you know what to update? I assume I run the `build.ps1` script, but then what, just replace some dll somewhere, I guess?

**Comment by deviousasti** [comment]
I've released 1.1.0 on the marketplace.
You should be able to go Extensions > Manage Extensions > Update and
install the new version.

**Comment by abelbraaksma** [comment]
Oh, yes, that'd work too! 😄

**Comment by abelbraaksma** [comment]
That's an interesting error, as I installed the tool globally with the `-g` flag. Also, the Fantomas plugin worked in other projects. 

However, good news is that after doing a `dotnet tool restore` on the root of the project that didn't work, it now picks it up correctly. Is it possible that if fantomas is configured for a project that it does not attempt to find the tool on the global path?

**Comment by deviousasti** [comment]
>  Is it possible that if fantomas is configured for a project that it does not attempt to find the tool on the global path?
Yes, this is the current behavior.

**Comment by Nekroido** [comment]
Yup, it's much clearer where the issue lies now. I can confirm the "file came from another computer" error. I guess I'm out of luck and I need to consider setting up my dev env in Windows host. Unless it's possible to skip loading `dotnet-tools.json` and use the globally installed tool instead.

**Comment by nojaf** [comment]
The flow is the following:
It will check if you have a local tool (using `dotnet tool list`),
next, it will check if it has a global tool (using `dotnet tool list -g`).

So, if you have a global tool in both places that might work but I suspect you will bump into problems when detecting the `.editorconfig`.

**Comment by deviousasti** [comment]
On WSL2, if there's no local config, I can confirm that the file formats with the global tool.

**Comment by sonicbhoc** [comment]
I too am running into this. Is there a way to configure Fantomas to look for a global tool if the local tool fails with this specific error?
