### ISSUE TITLE
Unable to install the extension to VS 2022 on ARM64

### ISSUE THREAD

**Issue by dahlia** [fsprojects/fantomas-for-vs#42]
I tried to install the extension to Visual Studio Community 2022 (ARM 64-bit) on Windows 11 Pro (ARM64).  Here's the log:

~~~~
12/7/2022 1:24:16 AM - Microsoft VSIX Installer
12/7/2022 1:24:16 AM - -------------------------------------------
12/7/2022 1:24:16 AM - vsixinstaller.exe version:
12/7/2022 1:24:16 AM - 17.4.2118-17-4P4Inse-ge4c88902
12/7/2022 1:24:16 AM - -------------------------------------------
12/7/2022 1:24:16 AM - Command line parameters:
12/7/2022 1:24:16 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\hongm\Downloads\FantomasVs.vsix
12/7/2022 1:24:16 AM - -------------------------------------------
12/7/2022 1:24:16 AM - Microsoft VSIX Installer
12/7/2022 1:24:16 AM - -------------------------------------------
12/7/2022 1:24:17 AM - Initializing Install...
12/7/2022 1:24:18 AM - Extension Details...
12/7/2022 1:24:18 AM - 	Identifier         : FantomasVs.4acfe0e3-4521-45ed-9c32-9265806f4108
12/7/2022 1:24:18 AM - 	Name               : F# Formatting
12/7/2022 1:24:18 AM - 	Author             : Asti
12/7/2022 1:24:18 AM - 	Version            : 1.1.0
12/7/2022 1:24:18 AM - 	Description        : F# source code formatting using Fantomas. 
12/7/2022 1:24:18 AM - 	Locale             : en-US
12/7/2022 1:24:18 AM - 	MoreInfoURL        : https://github.com/deviousasti/fsharp-formatting-for-vs
12/7/2022 1:24:18 AM - 	InstalledByMSI     : False
12/7/2022 1:24:18 AM - 	SupportedFrameworkVersionRange : [4.5,)
12/7/2022 1:24:18 AM - 
12/7/2022 1:24:18 AM - 	SignatureState     : Unsigned
12/7/2022 1:24:18 AM - 	Supported Products : 
12/7/2022 1:24:18 AM - 		Microsoft.VisualStudio.Community
12/7/2022 1:24:18 AM - 			Version : [17.0,18.0)
12/7/2022 1:24:18 AM - 			ProductArchitecture : amd64
12/7/2022 1:24:18 AM - 
12/7/2022 1:24:18 AM - 	References         : 
12/7/2022 1:24:18 AM - 	Prerequisites      : 
12/7/2022 1:24:18 AM - 		-------------------------------------------------------
12/7/2022 1:24:18 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
12/7/2022 1:24:18 AM - 		Name         : Visual Studio core editor
12/7/2022 1:24:18 AM - 		Version      : [17.0,18.0)
12/7/2022 1:24:18 AM - 
12/7/2022 1:24:18 AM - Signature Details...
12/7/2022 1:24:18 AM - 	Extension is not signed.
12/7/2022 1:24:18 AM - 
12/7/2022 1:24:18 AM - Searching for applicable products...
12/7/2022 1:24:18 AM - Found installed product - Global Location
12/7/2022 1:24:18 AM - Found installed product - Visual Studio Community 2022
12/7/2022 1:24:18 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
~~~~

**Comment by majocha** [comment]
Hi @deviousasti, I tried to add arm64 target: [https://github.com/majocha/fantomas-for-vs/commit/0b63c04a118d9aa3b7dd8bb833394f17cb0972ab](https://github.com/majocha/fantomas-for-vs/commit/0b63c04a118d9aa3b7dd8bb833394f17cb0972ab)
 and at least it didn't break anything. The extension still builds fine and works fine on normal 64bit VS2022. There seems to be no harm in adding arm64.
