### ISSUE TITLE
Error in format files inside Visual Studio after updating fantomas to 6.0.0-alpha-010

### ISSUE THREAD

**Issue by zyzhu** [fsprojects/fantomas-for-vs#48]
Just updated fantomas to 6.0.0-alpha-010. Command line worked like a charm to format all files. However, format inside Visual Studio showed the following error.

```
ParseException
  [{ Severity = Error
     SubCategory = "parse"
     Range = None
     ErrorNumber = None
     Message =
      "A type definition requires one or more members or other declarations. If you intend to define an empty class, struct or interface, then use 'type ... = class end', 'interface end' or 'struct end'." };
   { Severity = Error
     SubCategory = "parse"
     Range = Some (11,4--11,6)
     ErrorNumber = Some 10
     Message = "Unexpected symbol '[<' in expression" };
   { Severity = Error
     SubCategory = "parse"
     Range = None
     ErrorNumber = None
     Message = "Unmatched '{'" };
   { Severity = Error
     SubCategory = "parse"
     Range = Some (23,4--23,5)
     ErrorNumber = Some 10
     Message =
      "Incomplete structured construct at or before this point in implementation file" }]
Attempting to find Fantomas Tool...
Found at: FantomasToolFound
  (FantomasVersion "6.0.0-alpha-010",
   LocalTool (Folder "C:\FSharp\KARP\DeedleHelper\DeedleHelper.Math"))
The formatting operation failed:
 System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonSerializationException: Deserializing JSON-RPC result to type FormatDocumentResponse failed with JsonSerializationException: The number of field values does not match the number of properties defined by union 'Formatted'. Path 'result'.
   at StreamJsonRpc.JsonMessageFormatter.JsonRpcResult.GetResult[T]()
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Fantomas.Client.LSPFantomasService.Fantomas-Client-Contracts-FantomasService-FormatDocumentAsync@276-1.Invoke(Task`1 t) in C:\Users\nojaf\Projects\fantomas\src\Fantomas.Client\LSPFantomasService.fs:line 276
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FantomasVs.FantomasHandler.<FormatAsync>d__8.MoveNext()
---> (Inner Exception #0) Newtonsoft.Json.JsonSerializationException: Deserializing JSON-RPC result to type FormatDocumentResponse failed with JsonSerializationException: The number of field values does not match the number of properties defined by union 'Formatted'. Path 'result'.
   at StreamJsonRpc.JsonMessageFormatter.JsonRpcResult.GetResult[T]()
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()<---

The formatting operation failed:
 System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonSerializationException: Deserializing JSON-RPC result to type FormatDocumentResponse failed with JsonSerializationException: The number of field values does not match the number of properties defined by union 'Formatted'. Path 'result'.
   at StreamJsonRpc.JsonMessageFormatter.JsonRpcResult.GetResult[T]()
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Fantomas.Client.LSPFantomasService.Fantomas-Client-Contracts-FantomasService-FormatDocumentAsync@276-1.Invoke(Task`1 t) in C:\Users\nojaf\Projects\fantomas\src\Fantomas.Client\LSPFantomasService.fs:line 276
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FantomasVs.FantomasHandler.<FormatAsync>d__8.MoveNext()
---> (Inner Exception #0) Newtonsoft.Json.JsonSerializationException: Deserializing JSON-RPC result to type FormatDocumentResponse failed with JsonSerializationException: The number of field values does not match the number of properties defined by union 'Formatted'. Path 'result'.
   at StreamJsonRpc.JsonMessageFormatter.JsonRpcResult.GetResult[T]()
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()<---
```

My .editorconfig
```
indent_size = 4
tab_size = 4
max_line_length = 100
fsharp_max_value_binding_width = 60
fsharp_max_function_binding_width = 60
fsharp_max_infix_operator_expression = 60
fsharp_max_dot_get_expression_width = 60
fsharp_multi_line_lambda_closing_newline = true
fsharp_blank_lines_around_nested_multiline_expressions = false
fsharp_space_before_lowercase_invocation = false
fsharp_multiline_bracket_style = stroustrup
fsharp_newline_before_multiline_computation_expression = false
```

Visual Studio version: 17.4.5

**Comment by nojaf** [comment]
Hello, we are aware of this problem and the extension should bump [Fantomas.Client](https://www.nuget.org/packages/Fantomas.Client/0.9.0) to support `v6`.

@deviousasti could you bump and make a new release for this please?

**Comment by zyzhu** [comment]
Thanks. @nojaf May I suggest that you be added to the owner of the VS extension so that the future release will be more synchronized. Auto formatting in VS is part of the day-to-day workflow using Fantomas.

**Comment by nojaf** [comment]
I don't think I'm a good candidate here as I don't use VS at all.
To address future `Fantomas.Client` updates I've raised https://github.com/fsprojects/fantomas-for-vs/pull/49.

**Comment by zyzhu** [comment]
In that sense, maybe somebody from MS team could be added as a backup admin of this extension so that VS users are always covered. @dsyme

**Comment by zyzhu** [comment]
Hi @deviousasti, sorry to bother you here. Could you merge the pulls that bumped Fantomas.Client from 0.4.0 to 0.9.0 and release the new extension to VS Marketplace? The VS auto formatting is broken with latest Fantomas release. Thanks for your help!

**Comment by deviousasti** [comment]
@zyzhu 
Sorry, the client upgrade was breaking - I've pushed an update to VS22 for now, but I will need to work on #52 to make it work for VS19 - it's completely broken at the moment.

**Comment by zyzhu** [comment]
Thanks for your quick turnaround. It works perfectly in VS 2022 now. Hope VS 2019 can be retired someday soon.
